name: Deploy Backend and Frontend to Production

on:
  # just to testing
  pull_request:
    branches:
      - production
  push:
    branches:
      - production

jobs:
  deploy-production:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.4

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build packages only
        run: bun run build --filter='@interviews-tool/*'

      # - name: Deploy Frontend to Alchemy
      #   working-directory: apps/web
      #   env:
      #     ENVIRONMENT: production
      #     VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
      #     ALCHEMY_PASSWORD: ${{ secrets.ALCHEMY_PASSWORD }}
      #     CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
      #     CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
      #     BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      #     BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
      #   run: bun run deploy
      - name: Deploy Server to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: apps/server
          secrets: |
            DATABASE_URL
            DATABASE_URL_DIRECT
            CORS_ORIGIN
            BETTER_AUTH_SECRET
            BETTER_AUTH_URL
        # env:
        #   DATABASE_URL: ${{ secrets.DATABASE_URL }}
        #   DATABASE_URL_DIRECT: ${{ secrets.DATABASE_URL_DIRECT }}
        #   CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
        #   BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
        #   BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
